// <auto-generated />
using Fiap.Services.PromocaoAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fiap.Services.PromocaoAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230529174511_AddPromocaoDb")]
    partial class AddPromocaoDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Services.PromocaoAPI.Models.Promocao", b =>
                {
                    b.Property<int>("PromocaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromocaoId"));

                    b.Property<string>("CodigoPromocional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Desconto")
                        .HasColumnType("float");

                    b.HasKey("PromocaoId");

                    b.ToTable("Promocoes");

                    b.HasData(
                        new
                        {
                            PromocaoId = 1,
                            CodigoPromocional = "10OFF",
                            Desconto = 10.0
                        },
                        new
                        {
                            PromocaoId = 2,
                            CodigoPromocional = "20OFF",
                            Desconto = 20.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
