// <auto-generated />
using Fiap.Services.CarrinhoAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fiap.Services.CarrinhoAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Services.CarrinhoAPI.Models.CarrinhoDetalhe", b =>
                {
                    b.Property<int>("CarrinhoDetalheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarrinhoDetalheId"));

                    b.Property<int>("CarrinhoPedidoId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.HasKey("CarrinhoDetalheId");

                    b.HasIndex("CarrinhoPedidoId");

                    b.HasIndex("CursoId");

                    b.ToTable("CarrinhoDetalhes");
                });

            modelBuilder.Entity("Fiap.Services.CarrinhoAPI.Models.CarrinhoPedido", b =>
                {
                    b.Property<int>("CarrinhoPedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarrinhoPedidoId"));

                    b.Property<string>("CodigoPromocional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarrinhoPedidoId");

                    b.ToTable("CarrinhoPedidos");
                });

            modelBuilder.Entity("Fiap.Services.CarrinhoAPI.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Fiap.Services.CarrinhoAPI.Models.CarrinhoDetalhe", b =>
                {
                    b.HasOne("Fiap.Services.CarrinhoAPI.Models.CarrinhoPedido", "CarrinhoPedido")
                        .WithMany()
                        .HasForeignKey("CarrinhoPedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Services.CarrinhoAPI.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarrinhoPedido");

                    b.Navigation("Curso");
                });
#pragma warning restore 612, 618
        }
    }
}
